#!/usr/bin/env bash

DYLIB_DIR="$HOME/.local/lib"

COMPILER="clang++"
CPP_FLAGS="-std=c++14 -Wall -Wextra -O3"
LD_FLAGS="-Wl,-search_paths_first -Wl,-headerpad_max_install_names -Wl,-rpath,/Users/ajc/.local/lib"

BIN_DIR="bin"

INC_DIRS="-isystem/usr/local/include/eigen3 -isystem$HOME/.local/include -isystem/usr/local/include/bullet"
LIB_DIRS="-L$DYLIB_DIR"
LIBS="-ldart -lassimp -lBulletCollision -lLinearMath -ldart-collision-bullet"

export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$DYLIB_DIR


function erun () {
    echo $@
    $@
}


function compile () {
    if [ -z "$3" ]; then
        DEF=""
        BIN_NAME=$BIN_DIR/$2
    else
        DEF="-D$3"
        BIN_NAME=$BIN_DIR/$2_vis
    fi
    erun $COMPILER $CPP_FLAGS $LD_FLAGS $INC_DIRS $LIB_DIRS $LIBS $1/$2.cpp -o $BIN_NAME $DEF
}


function build () {
    if [ -d "$1" ]; then
        compile "$1" "$1" "$2"
    else
        printf "Error: could not find \"""$1""\"\n"
    fi
}


# Create a bin directory
mkdir -p $BIN_DIR


case "$1" in
    clean )
        rm -rf "$BIN_DIR"
        ;;

    build )
        build ${2%/} "$3"
        ;;

    * )
        printf "Error: unknown command \"""$1""\"\n"
        ;;
esac
